// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * H​e​l​l​o​ ​{​n​a​m​e​}​!
	 * @param {unknown} name
	 */
	hello: RequiredParams<'name'>
}

export type TranslationFunctions = {
	/**
	 * Hello {name}!
	 */
	hello: (arg: { name: unknown }) => LocalizedString
}

export type Formatters = {}
